### ISSUE TITLE
Alles

### ISSUE THREAD

**Issue by marcelago** [Crazyroostereye1/docs#5]
So ziemlich :(

**Comment by Crazyroostereye1** [comment]
Hey was soll das

**Comment by marcelago** [comment]
;)Sent from Android deviceAm 02.05.2023 16:51 schrieb Crazyroostereye ***@***.***>:
Hey was soll das

**Comment by marcelago** [comment]
Ich mach nur spaßSent from Android deviceAm 02.05.2023 16:51 schrieb Crazyroostereye ***@***.***>:
Hey was soll das

**Comment by Crazyroostereye1** [comment]
Ich will nichts sagen aber deinen Antworten sind glaub I kaputt

**Comment by marcelago** [comment]
Echt, :( oh ich hab ne Teil mit ChatGPT gemacht, evt. ist was verrutscht Sent from Android deviceAm 02.05.2023 17:55 schrieb Crazyroostereye ***@***.***>:
Ich will nichts sagen aber deinen Antworten sind glaub I kaputt
